apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  namespace: doskoi
spec:
  replicas: 1  # 必要なレプリカ数
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: service_a_image:latest  # 使用するDockerイメージ
        ports:
        - containerPort: 3000  # コンテナがリッスンするポート
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-service
  namespace: doskoi
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: service-a