apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  namespace: doskoi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_aiu:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-service
  namespace: doskoi
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: service-a