# localにnginxをk8s上で動かすものです
apiVersion: apps/v1
kind: Deployment
metadata:
  name: honmono-dev-a-handson-nginx
  namespace: doskoi
  labels:
    app.kubernetes.io/name: nginx #何でもいいらしい
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx_a #ここでpodのラベル
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx_a #一致してないといけない
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 1234