apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  namespace: doskoi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_eoa:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
  namespace: doskoi
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app: service-b