apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  namespace: doskoi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_aiu:67e8076
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"]
        ports:
        - containerPort: 3000
        env:
        - name: ALLOWED_HOST
          value: 'service-b-service.doskoi.svc.cluster.local'
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "doskoi-service-a"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-service
  namespace: doskoi
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: service-a