name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418468932.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Images
        run: |
          docker build -t dos_img_aiu:latest ./ch14_aiu
          docker build -t dos_img_eoa:latest ./ch14_eoa

      - name: Tag Docker Images
        run: |
          docker tag dos_img_aiu:latest 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_aiu:latest
          docker tag dos_img_eoa:latest 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_eoa:latest

      - name: Push Docker Images to ECR
        run: |
          docker push 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_aiu:latest
          docker push 905418468932.dkr.ecr.us-east-1.amazonaws.com/dos_img_eoa:latest
