name: Rails Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_ch14_aiu:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3  # Gemfileで指定しているバージョンに変更
          bundler-cache: true

      - name: Print current directory
        run: echo "Current directory: $(pwd)"

      - name: List files in root
        run: ls -la

      - name: List files in ch14_aiu
        run: ls -la ./ch14_aiu

      - name: Install dependencies
        run: |
          echo "Changing to directory: ./ch14_aiu"
          cd ./ch14_aiu
          echo "Current directory: $(pwd)"
          bundle install

      - name: Set up database
        run: |
          echo "Changing to directory: ./ch14_aiu"
          cd ./ch14_aiu
          echo "Current directory: $(pwd)"
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DB_HOST: db
          DB_USERNAME: postgres
          DB_PASSWORD: password

      - name: Run tests
        run: |
          echo "Changing to directory: ./ch14_aiu"
          cd ./ch14_aiu
          echo "Current directory: $(pwd)"
          bundle exec rails test
        env:
          RAILS_ENV: test

  test_ch14_eoa:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3  # Gemfileで指定しているバージョンに変更
          bundler-cache: true

      - name: Print current directory
        run: echo "Current directory: $(pwd)"

      - name: List files in root
        run: ls -la

      - name: List files in ch14_eoa
        run: ls -la ./ch14_eoa

      - name: Install dependencies
        run: |
          echo "Changing to directory: ./ch14_eoa"
          cd ./ch14_eoa
          echo "Current directory: $(pwd)"
          bundle install

      - name: Set up database
        run: |
          echo "Changing to directory: ./ch14_eoa"
          cd ./ch14_eoa
          echo "Current directory: $(pwd)"
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DB_HOST: db
          DB_USERNAME: postgres
          DB_PASSWORD: password

      - name: Run tests
        run: |
          echo "Changing to directory: ./ch14_eoa"
          cd ./ch14_eoa
          echo "Current directory: $(pwd)"
          bundle exec rails test
        env:
          RAILS_ENV: test