name: Rubocop with Reviewdog

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rubocop:
    name: Rubocop linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop with Reviewdog
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          rubocop_extensions: rubocop-rails, rubocop-performance
          use_bundler: true
