name: Test AWS Secrets

on:
  push:
    branches:
      - main # またはテストしたい特定のブランチ

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test AWS Secrets Existence
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] || [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS secrets are missing"
            exit 1
          else
            echo "AWS secrets are set correctly"
          fi
